### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by malcolmst** [Burgos1337/ghidra-plugin-octogon#1]
Really great work here! It looks like you've added support for a large portion of the Hexagon instruction set.

I'm attempting to add some additional instructions from the V67 Reference Manual, and was wondering under which license (if any) you're willing to release this work?

**Comment by Burgos1337** [comment]
Thank you so much for your assessment! Sorry for being so late with my response - I have just added Apache License 2.0 to my repository, so I think everything is in it's place now. I hope this delay haven't caused much inconvenience for you, now you can specify the aspects that you want to add to this software using Apache License 2.0!

**Comment by malcolmst** [comment]
Much appreciated! No worries, and thanks again for all your hard work.
